name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    # Select Xcode version
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
      
    # Generate Keys.plist (Step 3)
    - name:  Translate secrets of base64 into json
      env:
          KEYS: ${{ secrets.KEYS_JSON }}
      run:
          echo $KEYS | base64 --decode > ./FancyDish/output.json
    - name:  Translate json into plist and generate Keys.plist
      run:
        plutil -convert xml1 ./FancyDish/output.json -o ./FancyDish/Keys.plist
    - name: Remove json file (Step 4)
      run:
        rm ./FancyDish/output.json

    # Run build
    - name: Build
      run: xcodebuild
            -scheme FancyDish
            -sdk iphonesimulator
            -configuration Debug
            build
    # Run unit test
    - name: Run tests
      run: xcodebuild
            -scheme FancyDish
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max'
            clean test
